In [2]:
import cv2
import matplotlib
from PIL import Image
import array
import numpy as np
from numpy import *
from random import gauss
from random import seed

In [3]:
grap = cv2.imread("test.png")
row_audio=len(grap)
print(row_audio)
print("grap modified")
ta= [ [ 0 for i in range(8) ] for j in range(row_audio) ]
i=0
j=0
while(j<row_audio):
    while(i<8):
       ta[j][i]=grap[j,i,2]
       i+=1
    j+=1
    i=0
print(ta) #pixel values



600
grap modified
[[0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 

In [4]:
        
#retrieving begins
tb= [ [ 0 for i in range(8) ] for k in range(row_audio) ]
k=0
i=0
while(k<row_audio):
   for i in range(8):
       if i==0:
           ta[k][i]=0*(256-ta[k][i])
       else:
           tb[k][i]=(ta[k][i])/(2**8)
       i+=1   
   k+=1
   i=0
print("decimal=")
print(tb)#converting i values back to decimal value

decimal=
[[0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0, 0.0, 0.0, 0.0, 0.0, 0.0, 0

In [5]:

sr= [ [ 0 for i in range(8) ] for j in range(row_audio) ]
key3= '5'
length=len(key3)
p=list();
for i in range(length):
   p.append(0)
w=0   
for v in key3:
   p[w]=int(v)
   w+=1   
w=0
v=0
print(p)#key3

j=0
i=0
l=0
while(j<row_audio):
   for l in p:
      if i>7:
         i=0
      else:
         sr[j][i]=tb[j][l]
      i+=1
      l+=1
   l=p[0]   
   j+=1
   i=0
print("interleaving retrieved")
print(sr)#interleaving done
o=0
p=0
#lsb changed

[5]
interleaving retrieved
[[0.0, 0, 0, 0, 0, 0, 0, 0], [0.0, 0, 0, 0, 0, 0, 0, 0], [0.0, 0, 0, 0, 0, 0, 0, 0], [0.0, 0, 0, 0, 0, 0, 0, 0], [0.0, 0, 0, 0, 0, 0, 0, 0], [0.0, 0, 0, 0, 0, 0, 0, 0], [0.0, 0, 0, 0, 0, 0, 0, 0], [0.0, 0, 0, 0, 0, 0, 0, 0], [0.0, 0, 0, 0, 0, 0, 0, 0], [0.0, 0, 0, 0, 0, 0, 0, 0], [0.0, 0, 0, 0, 0, 0, 0, 0], [0.0, 0, 0, 0, 0, 0, 0, 0], [0.0, 0, 0, 0, 0, 0, 0, 0], [0.0, 0, 0, 0, 0, 0, 0, 0], [0.0, 0, 0, 0, 0, 0, 0, 0], [0.0, 0, 0, 0, 0, 0, 0, 0], [0.0, 0, 0, 0, 0, 0, 0, 0], [0.0, 0, 0, 0, 0, 0, 0, 0], [0.0, 0, 0, 0, 0, 0, 0, 0], [0.0, 0, 0, 0, 0, 0, 0, 0], [0.0, 0, 0, 0, 0, 0, 0, 0], [0.0, 0, 0, 0, 0, 0, 0, 0], [0.0, 0, 0, 0, 0, 0, 0, 0], [0.0, 0, 0, 0, 0, 0, 0, 0], [0.0, 0, 0, 0, 0, 0, 0, 0], [0.0, 0, 0, 0, 0, 0, 0, 0], [0.0, 0, 0, 0, 0, 0, 0, 0], [0.0, 0, 0, 0, 0, 0, 0, 0], [0.0, 0, 0, 0, 0, 0, 0, 0], [0.0, 0, 0, 0, 0, 0, 0, 0], [0.0, 0, 0, 0, 0, 0, 0, 0], [0.0, 0, 0, 0, 0, 0, 0, 0], [0.0, 0, 0, 0, 0, 0, 0, 0], [0.0, 0, 0, 0, 0, 0, 0, 0], [0.0, 0, 0, 0, 0, 0,

In [6]:
seed(1)

print(seed(1))

None


In [7]:
series1r= [gauss(0.0, 1.0) for i in range(row_audio*8)]
print(series1r)

[1.2881847531554629, 1.449445608699771, 0.06633580893826191, -0.7645436509716318, -1.0921732151041414, 0.03133451683171687, -1.022103170010873, -1.4368294451025299, 0.19931197648375384, 0.13337460465860485, 0.5464683003382316, -0.9139709437353126, 0.005005283626572444, -0.06474176037268789, -1.5058290012607418, 0.5379971786610338, 0.32071110099884825, 2.389112043240686, 0.20296917730996422, -0.14470230816492052, 1.2327571750289237, 0.1987912481934255, 0.9090310261532091, -0.3655442662325168, 0.21817181336058245, 1.024288678487018, 0.6962470224529616, 0.1284722486328564, -1.0823080245960446, 0.44522177236104854, 0.07686348171925232, 0.7204675968592537, 0.21623293780007305, 1.0881854111355231, -0.051560265423925424, 0.20196406007942128, 0.6667764386256495, -1.0868846121744795, -0.4016602600740189, -0.5000285689523685, 1.980615719523246, -0.09286202565608458, 0.652220223807572, 0.619375062173719, -0.2808734301868926, -1.5508368271304471, 0.9648439706761432, -0.40719676966359186, 0.7179566

In [8]:
seriesr=reshape(series1r,(row_audio,8))
print(seriesr)

[[ 1.28818475  1.44944561  0.06633581 ...  0.03133452 -1.02210317
  -1.43682945]
 [ 0.19931198  0.1333746   0.5464683  ... -0.06474176 -1.505829
   0.53799718]
 [ 0.3207111   2.38911204  0.20296918 ...  0.19879125  0.90903103
  -0.36554427]
 ...
 [-0.02381669  1.74850351 -0.82909596 ... -0.61235589  0.52680614
  -1.18164361]
 [-1.92774276  1.85725642  1.18357567 ... -0.30013112  0.77849818
  -0.94385836]
 [-0.81542743 -0.28324685  0.06220517 ...  0.08893602 -0.6496427
  -0.20056576]]


In [9]:
minir=seriesr.min()
print(minir)

-3.149965016046237


In [10]:
zr=seriesr-minir
print(zr)

[[4.43814977 4.59941062 3.21630082 ... 3.18129953 2.12786185 1.71313557]
 [3.34927699 3.28333962 3.69643332 ... 3.08522326 1.64413601 3.68796219]
 [3.47067612 5.53907706 3.35293419 ... 3.34875626 4.05899604 2.78442075]
 ...
 [3.12614832 4.89846853 2.32086905 ... 2.53760912 3.67677116 1.96832141]
 [1.22222226 5.00722144 4.33354068 ... 2.84983389 3.9284632  2.20610665]
 [2.33453759 2.86671817 3.21217018 ... 3.23890103 2.50032231 2.94939926]]


In [11]:
maxir=zr.max()
print(maxir)

6.550516932488211


In [12]:
qr=maxir/2**7
print(qr)

0.05117591353506415


In [13]:
audior=fix(zr/qr)
print(audior)

[[ 86.  89.  62. ...  62.  41.  33.]
 [ 65.  64.  72. ...  60.  32.  72.]
 [ 67. 108.  65. ...  65.  79.  54.]
 ...
 [ 61.  95.  45. ...  49.  71.  38.]
 [ 23.  97.  84. ...  55.  76.  43.]
 [ 45.  56.  62. ...  63.  48.  57.]]


In [14]:

# create white noise series;not displayed here
signal1r=audior/audior.max()
print(signal1r)


[[0.671875  0.6953125 0.484375  ... 0.484375  0.3203125 0.2578125]
 [0.5078125 0.5       0.5625    ... 0.46875   0.25      0.5625   ]
 [0.5234375 0.84375   0.5078125 ... 0.5078125 0.6171875 0.421875 ]
 ...
 [0.4765625 0.7421875 0.3515625 ... 0.3828125 0.5546875 0.296875 ]
 [0.1796875 0.7578125 0.65625   ... 0.4296875 0.59375   0.3359375]
 [0.3515625 0.4375    0.484375  ... 0.4921875 0.375     0.4453125]]


In [15]:
signalr= [ [ 0 for i in range(8) ] for j in range(row_audio) ]
key2= '23'
lengt=len(key2)
qr=list();
for i in range(lengt):
   qr.append(0)
w=0   
for p in key2:
   qr[w]=int(p)
   w+=1   
w=0
p=0
print(qr)#key2

[2, 3]


In [21]:
j=0
i=0
l=0
while(j<row_audio):
   for l in qr:
      if i>7:
         i=0
      else:
         signalr[j][i]=(signal1r[j][l])
         # print(signalr)
      i+=1
      l+=1
   l=qr[0]   
   j+=1
   i=0
print("noice signal")
print(signalr)
#Noise generated;not displayed

noice signal
[[0.484375, 0.359375, 0, 0, 0, 0, 0, 0], [0.5625, 0.3359375, 0, 0, 0, 0, 0, 0], [0.5078125, 0.453125, 0, 0, 0, 0, 0, 0], [0.5859375, 0.5, 0, 0, 0, 0, 0, 0], [0.46875, 0.5078125, 0, 0, 0, 0, 0, 0], [0.578125, 0.5703125, 0, 0, 0, 0, 0, 0], [0.40625, 0.671875, 0, 0, 0, 0, 0, 0], [0.5234375, 0.328125, 0, 0, 0, 0, 0, 0], [0.2109375, 0.4609375, 0, 0, 0, 0, 0, 0], [0.6796875, 0.453125, 0, 0, 0, 0, 0, 0], [0.546875, 0.390625, 0, 0, 0, 0, 0, 0], [0.4921875, 0.46875, 0, 0, 0, 0, 0, 0], [0.328125, 0.4140625, 0, 0, 0, 0, 0, 0], [0.390625, 0.5859375, 0, 0, 0, 0, 0, 0], [0.5625, 0.65625, 0, 0, 0, 0, 0, 0], [0.4453125, 0.421875, 0, 0, 0, 0, 0, 0], [0.4453125, 0.5234375, 0, 0, 0, 0, 0, 0], [0.3984375, 0.6328125, 0, 0, 0, 0, 0, 0], [0.375, 0.46875, 0, 0, 0, 0, 0, 0], [0.6015625, 0.6796875, 0, 0, 0, 0, 0, 0], [0.515625, 0.6953125, 0, 0, 0, 0, 0, 0], [0.78125, 0.4140625, 0, 0, 0, 0, 0, 0], [0.4765625, 0.5, 0, 0, 0, 0, 0, 0], [0.7578125, 0.171875, 0, 0, 0, 0, 0, 0], [0.3828125, 0.515625, 0, 0

In [17]:
Bir= [ [ 0 for i in range(8) ] for j in range(row_audio) ]
while(o<row_audio):
   while(p<8):
       try:
           Bir[o][p]=((sr[o][p]/signalr[o][p]))
       except:
           Bir[0][p]=0
       p+=1  
   o+=1   
   p=0  #embedded signal(product of message signal and noise)
o=0
p=0
print("embeddeed signal")
print(Bir)

embeddeed signal
[[0.0, 0.0, 0, 0, 0, 0, 0, 0], [0.0, 0.0, 0, 0, 0, 0, 0, 0], [0.0, 0.0, 0, 0, 0, 0, 0, 0], [0.0, 0.0, 0, 0, 0, 0, 0, 0], [0.0, 0.0, 0, 0, 0, 0, 0, 0], [0.0, 0.0, 0, 0, 0, 0, 0, 0], [0.0, 0.0, 0, 0, 0, 0, 0, 0], [0.0, 0.0, 0, 0, 0, 0, 0, 0], [0.0, 0.0, 0, 0, 0, 0, 0, 0], [0.0, 0.0, 0, 0, 0, 0, 0, 0], [0.0, 0.0, 0, 0, 0, 0, 0, 0], [0.0, 0.0, 0, 0, 0, 0, 0, 0], [0.0, 0.0, 0, 0, 0, 0, 0, 0], [0.0, 0.0, 0, 0, 0, 0, 0, 0], [0.0, 0.0, 0, 0, 0, 0, 0, 0], [0.0, 0.0, 0, 0, 0, 0, 0, 0], [0.0, 0.0, 0, 0, 0, 0, 0, 0], [0.0, 0.0, 0, 0, 0, 0, 0, 0], [0.0, 0.0, 0, 0, 0, 0, 0, 0], [0.0, 0.0, 0, 0, 0, 0, 0, 0], [0.0, 0.0, 0, 0, 0, 0, 0, 0], [0.0, 0.0, 0, 0, 0, 0, 0, 0], [0.0, 0.0, 0, 0, 0, 0, 0, 0], [0.0, 0.0, 0, 0, 0, 0, 0, 0], [0.0, 0.0, 0, 0, 0, 0, 0, 0], [0.0, 0.0, 0, 0, 0, 0, 0, 0], [0.0, 0.0, 0, 0, 0, 0, 0, 0], [0.0, 0.0, 0, 0, 0, 0, 0, 0], [0.0, 0.0, 0, 0, 0, 0, 0, 0], [0.0, 0.0, 0, 0, 0, 0, 0, 0], [0.0, 0.0, 0, 0, 0, 0, 0, 0], [0.0, 0.0, 0, 0, 0, 0, 0, 0], [0.0, 0.0, 0, 0, 0, 0,

In [28]:
key = '15'
lenge=len(key)
o=list();
for i in range(lenge):
   o.append(0)  #initializing
j=0

for i in key:
    o[j]=int(i)
    j+=1   
j=0
i=0

bir= [ [ 0 for i in range(8) ] for j in range(row_audio//8) ]
# print(bir)
print(o)#key 1 displayed
while(j<row_audio//8):
   for l in o:
      if i>7:
          i=0
      if j>0:
         bir[j][i]=Bir[l+(8*j)][7]
         print(bir)
      else:
         bir[j][i]=Bir[l][7]
      i+=1
   j+=1
   i=0
print("lsb changed")
print(Bir[l][7])
print(bir)

[1, 5]
[[0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 

In [19]:

i=0
j=0
while(j<row_audio//8):
   while(i<8):
      if bir[j][i]==-1.0:
         bir[j][i]=0
         # print('bir : ')
         # print(bir)
      else:
         bir[j][i]=1
      i+=1
   j+=1   
   i=0
i=0
j=0
print(bir)#converting -1s to 0s

[[1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1

In [20]:

var=[0 for i in range(row_audio//8)]
i=7
j=0
while(j<row_audio/8):
   sommy=0
   while(i>-1):
      sommy+=bir[j][i]*(2**(7-i))
      i-=1
   var[j]=sommy
   # print('var[j] : ')
   # print(var[j])
   j+=1   
   i=7
i=0
j=0
print((var[j]))#decimal values

for i in range(row_audio//8):
    if var[i]==92:
        break
    else:
       print(chr(var[i]))


255
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
